# Generated by Django 3.2 on 2021-05-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image_out_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_out_source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
