# Generated by Django 3.2 on 2021-07-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billid',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
